export class Employee{
  id:string;
  firstName:string;
  lastName:string;
  email:string;
  jobTitle:string;
  office:string;
  department:string;
  phone:string;
  skype:string;
  preferredName:string;
  constructor(args:any){
    args:args?args:{};
    this.id=args.id;
    this.firstName=args.firstName;
    this.lastName=args.lastName;
    this.email=args.email;
    this.jobTitle=args.jobTitle;
    this.office=args.office;
    this.department=args.department;
    this.phone=args.phone;
    this.skype=args.skype;
    this.preferredName=args.preferredName;
  }
}
